### ISSUE TITLE
Error on registration

### ISSUE THREAD

**Issue by 71619997a** [calctechie37/form#2]
When I attempt to register, I encounter an error. Traceback:
`File "app.py", line 38, in hi
    credentials.recordUserData(username, password)
  File "C:\Users\gmarks\Documents\CS\HW\tmp\form\util\credentials.py", line 14, in recordUserData
    file_.write(username + ", " + sha256(password).hexdigest() + '\n')
NameError: global name 'sha256' is not defined`
I believe this is caused by a missing import statement. This could be fixed if you added 
`from hashlib import sha256` to the beginning of util/credentials.py.

**Comment by calctechie37** [comment]
Thanks Mr. DW!  Forgot to check the dependencies when I shifted it to util.py.
